import "../styles/globals.css";
import { AuthProvider } from "./Providers";

export const metadata = {
  title: "Moviesweb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <AuthProvider>
            {children}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
